# Generated by Django 4.2.5 on 2023-09-27 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='product',
            new_name='prod',
        ),
        migrations.AddField(
            model_name='product',
            name='vers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.version', verbose_name='Версия'),
        ),
    ]
