# Generated by Django 4.2.5 on 2024-07-18 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_alter_product_options_product_is_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "permissions": [
                    ("set_published_status", "Can publish product"),
                    ("can_edit_description", "Can edit description"),
                    ("can_edit_category", "Can edit category"),
                ],
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
    ]
